/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game_xo;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author ตาหวาน
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        p03.hide();
        p02.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p01 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p02 = new javax.swing.JPanel();
        j1 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        m2 = new javax.swing.JTextField();
        j2 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        start1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p03 = new javax.swing.JPanel();
        G1 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        G9 = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        restart = new javax.swing.JButton();
        exit2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p01.setBackground(new java.awt.Color(153, 153, 153));
        p01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(111, 152, 180));
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        p01.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 0, 30, 30));

        t1.setFont(new java.awt.Font("Segoe Print", 1, 90)); // NOI18N
        t1.setForeground(new java.awt.Color(111, 152, 180));
        t1.setText("Tic Tac Toe");
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t1MouseExited(evt);
            }
        });
        p01.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 550, 90));

        start.setFont(new java.awt.Font("Segoe Print", 1, 50)); // NOI18N
        start.setForeground(new java.awt.Color(100, 124, 154));
        start.setText("Start Game");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });
        p01.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 340, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark-incense-smoke-wallpaper.jpg"))); // NOI18N
        p01.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 690));

        getContentPane().add(p01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 690));

        p02.setBackground(new java.awt.Color(102, 102, 102));
        p02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        j1.setForeground(new java.awt.Color(32, 55, 78));
        j1.setText("Player1 :");
        p02.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        m1.setBackground(new java.awt.Color(4, 4, 6));
        m1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        m1.setForeground(new java.awt.Color(32, 55, 78));
        m1.setText("name1");
        m1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(100, 124, 154)));
        m1.setOpaque(false);
        m1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m1MouseClicked(evt);
            }
        });
        p02.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 210, 50));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("VS");
        p02.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        m2.setBackground(new java.awt.Color(4, 4, 6));
        m2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        m2.setForeground(new java.awt.Color(32, 55, 78));
        m2.setText("name2");
        m2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(100, 124, 154)));
        m2.setOpaque(false);
        m2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2MouseClicked(evt);
            }
        });
        p02.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 210, 50));

        j2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        j2.setForeground(new java.awt.Color(32, 55, 78));
        j2.setText("Player2 :");
        p02.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        exit1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        exit1.setForeground(new java.awt.Color(111, 152, 180));
        exit1.setText("x");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit1MouseExited(evt);
            }
        });
        p02.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 0, 30, 30));

        start1.setFont(new java.awt.Font("Segoe Print", 1, 50)); // NOI18N
        start1.setForeground(new java.awt.Color(100, 124, 154));
        start1.setText("Start Game");
        start1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                start1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                start1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                start1MouseExited(evt);
            }
        });
        p02.add(start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 340, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dark-incense-smoke-wallpaper.jpg"))); // NOI18N
        p02.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 690));

        getContentPane().add(p02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 690));

        p03.setBackground(new java.awt.Color(204, 204, 204));
        p03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        G1.setBackground(new java.awt.Color(93, 144, 173));
        G1.setForeground(new java.awt.Color(93, 144, 173));
        G1.setBorder(null);
        G1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G1ActionPerformed(evt);
            }
        });
        p03.add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, 100));

        G2.setBackground(new java.awt.Color(93, 144, 173));
        G2.setForeground(new java.awt.Color(93, 144, 173));
        G2.setBorder(null);
        G2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G2ActionPerformed(evt);
            }
        });
        p03.add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 100));

        G3.setBackground(new java.awt.Color(93, 144, 173));
        G3.setForeground(new java.awt.Color(93, 144, 173));
        G3.setBorder(null);
        G3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G3ActionPerformed(evt);
            }
        });
        p03.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 100, 100));

        G4.setBackground(new java.awt.Color(93, 144, 173));
        G4.setForeground(new java.awt.Color(93, 144, 173));
        G4.setBorder(null);
        G4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G4ActionPerformed(evt);
            }
        });
        p03.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 100, 100));

        G5.setBackground(new java.awt.Color(93, 144, 173));
        G5.setForeground(new java.awt.Color(93, 144, 173));
        G5.setBorder(null);
        G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5ActionPerformed(evt);
            }
        });
        p03.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, 100));

        G6.setBackground(new java.awt.Color(93, 144, 173));
        G6.setForeground(new java.awt.Color(93, 144, 173));
        G6.setBorder(null);
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });
        p03.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, 100));

        G7.setBackground(new java.awt.Color(93, 144, 173));
        G7.setForeground(new java.awt.Color(93, 144, 173));
        G7.setBorder(null);
        G7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G7ActionPerformed(evt);
            }
        });
        p03.add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 100, 100));

        G8.setBackground(new java.awt.Color(93, 144, 173));
        G8.setForeground(new java.awt.Color(93, 144, 173));
        G8.setBorder(null);
        G8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G8ActionPerformed(evt);
            }
        });
        p03.add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 100, 100));

        G9.setBackground(new java.awt.Color(93, 144, 173));
        G9.setForeground(new java.awt.Color(93, 144, 173));
        G9.setBorder(null);
        G9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G9ActionPerformed(evt);
            }
        });
        p03.add(G9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 100, 100));

        name2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        name2.setForeground(new java.awt.Color(100, 124, 154));
        name2.setText("Player2 :");
        p03.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 220, 50));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 124, 154));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_Spider-Man_Head_60px_1.png"))); // NOI18N
        p03.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 60, 70));

        name.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(100, 124, 154));
        name.setText("Player1 :");
        p03.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 50));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(100, 124, 154));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xxx.png"))); // NOI18N
        p03.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 60));

        score1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        score1.setForeground(new java.awt.Color(100, 124, 154));
        score1.setText("Score :");
        p03.add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 50));

        score2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        score2.setForeground(new java.awt.Color(100, 124, 154));
        score2.setText("Score :");
        p03.add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 210, 50));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(100, 124, 154));
        jLabel10.setText("icon :");
        p03.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 60, 50));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(100, 124, 154));
        jLabel11.setText("icon :");
        p03.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 50));

        restart.setBackground(new java.awt.Color(54, 63, 72));
        restart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        restart.setForeground(new java.awt.Color(0, 153, 153));
        restart.setText("restart");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        p03.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 110, 40));

        exit2.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        exit2.setForeground(new java.awt.Color(111, 152, 180));
        exit2.setText("x");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit2MouseExited(evt);
            }
        });
        p03.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 0, 30, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/28063.jpg"))); // NOI18N
        p03.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, -20, 1220, 710));

        getContentPane().add(p03, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
      exit.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(new Color(111, 152, 180) );
    }//GEN-LAST:event_exitMouseExited

    private void t1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseEntered
       t1.setForeground(Color.BLACK);
    }//GEN-LAST:event_t1MouseEntered

    private void t1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseExited
        t1.setForeground(new Color(111, 152, 180) );
    }//GEN-LAST:event_t1MouseExited

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        start.setForeground(new Color(32, 55, 78));
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
         start.setForeground(new Color(100,124,154));
    }//GEN-LAST:event_startMouseExited

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
       //เปลี่ยนหน้า จาก p2 ไปp3
        //ว่อนหน้าที่ 2กับ 3 ก่อน
        p01.hide();
        p02.show();
    }//GEN-LAST:event_startMouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_exit1MouseClicked

    private void exit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseEntered
       exit1.setForeground(Color.BLACK);
    }//GEN-LAST:event_exit1MouseEntered

    private void exit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseExited
        exit1.setForeground(new Color(111, 152, 180) );
    }//GEN-LAST:event_exit1MouseExited

    private void m1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MouseClicked
        j1.setForeground(new Color(111,152,180));
        m1.setText("");//เวลากดมาตั้งชื่อมันจะเปลี่ยนในช่องให้เป็นค่าว่าง
    }//GEN-LAST:event_m1MouseClicked

    private void m2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MouseClicked
      j2.setForeground(new Color(111,152,180));
      m2.setText("");//ขออภัยลืม
            
    }//GEN-LAST:event_m2MouseClicked

    private void start1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start1MouseClicked
      p02.hide();
      p03.show();
      //นำชื่อไปโชว์ หน้าที่สาม
      name.setText("Player1 :"+m1.getText());
      name2.setText("Player2 :"+m2.getText());
    }//GEN-LAST:event_start1MouseClicked

    private void start1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start1MouseEntered
      start1.setForeground(new Color(32, 55, 78));
    }//GEN-LAST:event_start1MouseEntered

    private void start1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start1MouseExited
           start1.setForeground(new Color(100,124,154));
    }//GEN-LAST:event_start1MouseExited

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
       System.exit(WIDTH);
    }//GEN-LAST:event_exit2MouseClicked

    private void exit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseEntered
        exit2.setForeground(new Color(100,124,154));
    }//GEN-LAST:event_exit2MouseEntered

    private void exit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseExited
       exit2.setForeground(new Color(100,124,180));
    }//GEN-LAST:event_exit2MouseExited
     
    int i=1,P1=0,P2=0,P3=0,P4=0,P5=0,P6=0,P7=0,P8=0,P9=0;
    int c1=1,c2=1,c3=1,c4=1,c5=1,c6=1,c7=1,c8=1,c9=1;
    String M1="",M2="", M3="", M4="", M5="", M6="" ,M7="", M8="", M9=""; //ของ X
    String O1="",O2="", O3="", O4="", O5="", O6="" ,O7="", O8="", O9=""; //ของ X
    
     //นับการแต้มชนะ
    int S1=0;
    int S2=0;
    
    
    ImageIcon X =new ImageIcon(this.getClass().getResource("/X.png"));
    ImageIcon O =new ImageIcon(this.getClass().getResource("/O.png"));
    
    
    void check(){
      /*
        วิธีชนะมี ๕ แบบ
        
        | 1 | 2 | 3 |
        | 4 | 5 | 6 |
        | 7 | 8 | 9 | 
         
        1. 1 2 3
        2. 4 5 6
        3. 7 8 9
        4. 1 4 7
        5. 2 5 8
        6. 3 6 9
        7. 1 5 9
        8. 3 5 7
        */
   //        X         //    
   //1. 
        if(M1.equals("x")){
            if (M2.equals("x")) {
                if (M3.equals("x")) {
                JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                   score1.setText("Score : "+(++S1));
                }
            }
        }
    //2. 
        if(M4.equals("x")){
            if (M5.equals("x")) {
                if (M6.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                }
            }
        } 
    //3. 
        if(M7.equals("x")){
            if (M8.equals("x")) {
                if (M9.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                }
            }
        }    
    //4. 
        if(M1.equals("x")){
            if (M4.equals("x")) {
                if (M7.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                    
                }
            }
        }    
    //5. 
        if(M2.equals("x")){
            if (M5.equals("x")) {
                if (M8.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                }
            }
        } 
     //6. 
        if(M3.equals("x")){
            if (M6.equals("x")) {
                if (M9.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                }
            }
        }
    //7. 
        if(M1.equals("x")){
            if (M5.equals("x")) {
                if (M9.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re(); 
                    score1.setText("Score : "+(++S1));
                }
            }
        }
    //8. 
        if(M3.equals("x")){
            if (M5.equals("x")) {
                if (M7.equals("x")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,X); 
                   re();
                    score1.setText("Score : "+(++S1));
                }
            }
        }    
       //   O   //
       //1. 
        if(O1.equals("o")){
            if (O2.equals("o")) {
                if (O3.equals("o")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re();
                    score2.setText("Score : "+(++S2));
                }
            }
        }
    //2. 
        if(O4.equals("o")){
            if (O5.equals("o")) {
                if (O6.equals("o")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re();
                    score2.setText("Score : "+(++S2));
                }
            }
        } 
    //3. 
        if(O7.equals("o")){
            if (O8.equals("o")) {
                if (O9.equals("o")) {
                    JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re(); 
                    score2.setText("Score : "+(++S2));
                }
            }
        }    
    //4. 
        if(O1.equals("o")){
            if (O4.equals("o")) {
                if (O7.equals("o")) {
                    JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re(); 
                    score2.setText("Score : "+(++S2));
                }
            }
        }    
    //5. 
        if(O2.equals("o")){
            if (O5.equals("o")) {
                if (O8.equals("o")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re();
                    score2.setText("Score : "+(++S2));
                }
            }
        } 
     //6. 
        if(O3.equals("o")){
            if (O6.equals("o")) {
                if (O9.equals("o")) {
                     JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re();
                    score2.setText("Score : "+(++S2));
                }
            }
        }
    //7. 
        if(O1.equals("o")){
            if (O5.equals("o")) {
                if (O9.equals("o")) {
                   JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O); 
                   re();
                    score2.setText("Score : "+(++S2));
                }
            }
        }
    //8. 
        if(O3.equals("o")){
            if (O5.equals("o")) {
                if (O7.equals("o")) {
                    JOptionPane.showMessageDialog(null, "ผู้ชนะคือ  ", null,JOptionPane.INFORMATION_MESSAGE,O);
                    re();
                     score2.setText("Score : "+(++S2));
                }
            }
        }  
        
        
    }
  void re(){
       G1.setIcon(null);
        G2.setIcon(null);
        G3.setIcon(null);
        G4.setIcon(null);
        G5.setIcon(null);
        G6.setIcon(null);
        G7.setIcon(null);
        G8.setIcon(null);
        G9.setIcon(null);
        /*
         int i=1,P1=0,P2=0,P3=0,P4=0,P5=0,P6=0,P7=0,P8=0,P9=0;
    int c1=1,c2=1,c3=1,c4=1,c5=1,c6=1,c7=1,c8=1,c9=1;
    String M1="",M2="", M3="", M4="", M5="", M6="" ,M7="", M8="", M9=""; //ของ X
    String O1="",O2="", O3="", O4="", O5="", O6="" ,O7="", O8="", O9=""; //ของ X
    
        */
        i=0;
        P1=0;
        P2=0;
        P3=0;
        P4=0;
        P5=0;
        P6=0;
        P7=0;
        P8=0;
        P9=0;
       c1=1;
        c2=1;
         c3=1;
          c4=1;
           c5=1;
            c6=1;
             c7=1;
              c8=1; 
               c9=1;
                 M1="";
                 M2="";
                 M3="";
                 M4="";
                 M5="";
                 M6="";
                 M7="";
                 M8="";
                 M9="";
                 O1="";
                 O2="";
                 O3="";
                 O4="";
                 O5="";
                 O6="";
                 O7="";
                 O8="";
                 O9="";
  }  
    
    private void G1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G1ActionPerformed
      if(P1==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G1.setIcon(X);
                  P1++; M1="x";
              break;
          case 2: G1.setIcon(O);
                  P1++;   O1="o";
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      }   
      check();
    }//GEN-LAST:event_G1ActionPerformed

    private void G2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G2ActionPerformed
         if(P2==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G2.setIcon(X);
                  P2++;  M2="x";
              break;
          case 2: G2.setIcon(O);
                  P2++;   O2="o";
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      }
        check();
    }//GEN-LAST:event_G2ActionPerformed

    private void G3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G3ActionPerformed
           if(P3==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G3.setIcon(X);
                  P3++;  M3="x";
              break;
          case 2: G3.setIcon(O);
                  P3++;  O3="o"; 
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G3ActionPerformed

    private void G4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G4ActionPerformed
           if(P4==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G4.setIcon(X);
                  P4++;  M4="x";
              break;
          case 2: G4.setIcon(O);
                  P4++;   O4="o";
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G4ActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed
            if(P5==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G5.setIcon(X);
                  P5++;  M5="x";
              break;
          case 2: G5.setIcon(O);
                  P5++;   O5="o";
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G5ActionPerformed
 
    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
           if(P6==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G6.setIcon(X);
                  P6++;  M6="x";
              break;
          case 2: G6.setIcon(O);
                  P6++;  O6="o"; 
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G6ActionPerformed

    private void G7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G7ActionPerformed
           if(P7==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G7.setIcon(X);
                  P7++;  M7="x";
              break;
          case 2: G7.setIcon(O);
                  P7++; O7="o";  
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G7ActionPerformed

    private void G8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G8ActionPerformed
           if(P8==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G8.setIcon(X);
                  P8++;  M8="x";
              break;
          case 2: G8.setIcon(O);
                  P8++; O8="o";  
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G8ActionPerformed

    private void G9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G9ActionPerformed
           if(P9==0){  //ทำให้กดได้ครั้งเดียว ใส่เงื่อนไขครอบ
          switch(i)
      {
          case 1: G9.setIcon(X);
                  P9++;  M9="x";
              break;
          case 2: G9.setIcon(O);
                  P9++; 
                  O9="o";
              break;
      }
        if(i>2){
            i=1;
        }else{
            i++;
        }
      } check();
    }//GEN-LAST:event_G9ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
       re();             
              
        
    }//GEN-LAST:event_restartActionPerformed
      
   
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton G9;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name2;
    private javax.swing.JPanel p01;
    private javax.swing.JPanel p02;
    private javax.swing.JPanel p03;
    private javax.swing.JButton restart;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel start;
    private javax.swing.JLabel start1;
    private javax.swing.JLabel t1;
    // End of variables declaration//GEN-END:variables
}
